
package com.zanoccio.packetkit.headers.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * The {@link DynamicFragment} annotation indicates that a particular fragment
 * of a packet is generated by a method
 * 
 * @author wiktor
 * 
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface DynamicFragment {

	/**
	 * The position of this fragment within the packet
	 */
	int slot() default -1;


	/**
	 * The suggested buffer-size for this fragment of this packet. If the
	 * fragment is larger the buffer will automatically be resized, however,
	 * this is expensive, so it's best avoided.
	 */
	int buffersize() default 16;
}
